# videos
# _______________________________
# append youtube video id in the list to post it to website
video_arts:
  - id: lkblPY3n7y0

# site settings
# ______________________________
# name of the website
name: "Trezures Of Creations"
# github pages url
baseurl: https://ArtisticWorld.github.io
# repository name
scope:

# theme settings
# _______________________________
# use this google tool for finding hexcode for your fav color https://www.google.com/search?q=color+picker
# color of the theme on android phones
theme_color: "#b434eb"
# background color of caption page
caption_bg_color: "#7434eb"
# text color of captions
caption_text_color: "#fff"

# metadata settings
# _________________________________
# greetings on the gome page
greeting: "Hi!"
# author of the website
author: "Artistic World"
# heading on the home and about page
heading: "This is my Art Gallery"
# description of this website for about page and google search
description: "the digital collection of my special arts"

# graphics settings
# _____________________________________
# icon for browser
favicon: "assets/img/favicon.ico"
# logo for home and about page
logo: "assets/img/logo.png"
# author's personal pic for about page
pic: "assets/img/me.jpg"

# Author's details
# ________________________________________________
# author's email
email: "mp313652@gmail.com"
# author's socials
twitter:
facebook:
instagram:
youtube:
whatsapp:
google-plus:
linkedin:
spotify:
messenger:

# jekyll Settings
# _________________________________
collections:
  arts:
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-cayman
